[package]
name = "rust-sqlite-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-sqlite-lib = { version = "0.1.0", path = "../rust-sqlite-lib" }
rusqlite = { version = "0.35.0", features = ["bundled"] }
pretty-sqlite = "0.1.0"

[dev-dependencies]
pretty-sqlite = { version = "0.1.0" }
